### ISSUE TITLE
[milestone] v0.1.0 release

### ISSUE THREAD

**Issue by guangyuz** [zkmove/zkmove#116]
VM Release v0.1.0:
- [x] complex data type (add constraints for container/container_member value read/write)
- [x] new features: bitwise op (leave vectors, generic and const for v0.2.0)
- [x] zkmove/zkmove#112
- [x] global state
- [x] refactor, testing & bugfix (constraints completeness is not required)

SDK & MISC:
- [ ] documents (zkmove book?)
- [ ] playground(?)
- [ ] wasm(?)
- [x] website upgrade

**Comment by guangyuz** [comment]
container related bytecode:

pack/unpack
move_from/move_to
st_loc/copy_loc/move_loc

borrow_loc/borrow_global
borrow_field
read_ref/write_ref
