### ISSUE TITLE
TODO: what happens if vector len > u16

### ISSUE THREAD

**Issue by nanne007** [zkmove/zkmove#22]
related to [227](https://github.com/zkmove/zkmove/issues/52)

**Comment by guangyuz** [comment]
（updated to remove constraints on flen)

Regarding sub_index, we have already constrained the limb type in ExtendedSubIndex. We only need to ensure that the new limbs we concat are U16. 

Regarding the types of flen and len, we only need to constrain len to U16 when writing a new header or modifying an old header.

vec_push:

- [ ]  when update parent, require new header’s len is in range u16
- [ ]  write popped value to sub_index_vec_ref.concat(len+1), require len+1 ≤ max_u16

vec_pop:

- [ ]  when update parent, require new header’s  len is in range u16
- [ ]  read value from sub_index_vec_ref.concat(len), require len > 0

vec_swap:

- [ ]  similar to above…

pack/vec_pack:

- [ ]  check the new header:  If we want, we don’t need constrain len, because len = num_field, num_field is u16
- [ ]  for each row we have: `stack_push_sub_index(0) == stack_pop_sub_index(0) * DEPTH_POW_OF_ONE_LEVEL + field_index(0)`. We don’t need additional constraints, since field_index is < num_field (u16) by default.

unpack/vec_unpack:

- [ ]  no additional constraints needed.

write_ref:

- [ ]  new sub_index is constrained by extended_sub_index, no additional constraints needed.
`local_sub_index(0) == header_sub_index(0).concat(stack_pop_sub_index(0));`
- [ ]  update parents, no additional constraints needed.

**Comment by nanne007** [comment]
Why constrain `flen` to be u16?

**Comment by guangyuz** [comment]
> Why constrain `flen` to be u16?

oops! flen should be u128, assuming we fix sub_index to be [u16; 8]

**Comment by guangyuz** [comment]
actually the range check on flen is not necessary if sub_index is well constrained.
